### ISSUE TITLE
Kleine Frage zum Beenden

### ISSUE THREAD

**Issue by gustda** [nocheinheinrich/tic-tac-toe#1]
Hallo, ich hatte schon ein bisschen was [hier](https://github.com/LernMoment/ttt-challenge/issues/3) geschrieben, dort hattest du ja auch Fragen gestellt.
Nun habe ich eine Frage, wieso hast du das Spielende in das Spielbrett gesteckt? Hast du deinen speziellen Grund für? Wofür genau möchtest du diese Klasse verwenden?
Ich habe [hier](https://github.com/LernMoment/ttt-challenge/blob/master/README.md) gelesen, dass du neu bei C# bist, neu bei C# oder komplett in der Softwareentwicklung?

**Comment by nocheinheinrich** [comment]
Hallo Daniel,
erst einmal vielen Dank für Dein Feedback. Um Deine Frage zu beantworten: Ich bin Anfänger in C# und ebenfalls Anfänger in professioneller Softwareentwicklung. 
Warum ich das Spielende in das Spielbrett gesteckt habe? Zunächst einmal sollte das Spielende in eine eigene Methode. Da das Spielbrett hier das zentrale Element ist, bot sich das einfach deswegen an. Die Klasse hatte ich ja ohnehin schon.
